// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public extension Color {
    static let backgroundPrimary = Color(.sRGB, red: 0.078, green: 0.078, blue: 0.078, opacity: 1)
    static let backgroundElevated = Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 1)
    static let backgroundScrim = Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.6)
    static let textPrimary = Color(.sRGB, red: 1, green: 1, blue: 1, opacity: 1)
    static let textSecondary = Color(.sRGB, red: 0.502, green: 0.502, blue: 0.502, opacity: 1)
    static let actionPrimary = Color(.sRGB, red: 0.898, green: 0.035, blue: 0.078, opacity: 1)
    static let actionPrimaryPressed = Color(.sRGB, red: 0.698, green: 0.027, blue: 0.063, opacity: 1)
}
