// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public enum Radius {
    public static let sm: CGFloat = 2
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 20
    public static let full: CGFloat = 999
}
