// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public enum Radius {
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 8
}
