// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public enum Spacing {
    public static let none: CGFloat = 0
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
}
