// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public extension Font {
    static let bodyRegular = Font.custom("Inter", size: 17).weight(.regular)
    static let captionMedium = Font.custom("Inter", size: 14).weight(.medium)
    static let titleBold = Font.custom("Inter", size: 28).weight(.bold)
}

public enum LineHeight {
    public static let bodyRegular: CGFloat = 24
    public static let captionMedium: CGFloat = 20
    public static let titleBold: CGFloat = 34
}
