// Generated by @repo/design-tokens — do not edit.
// Source: packages/design-tokens/tokens/**

import SwiftUI

public extension Font {
    /// Titres d'écran pleine largeur (Coming Soon, Downloads).
    static let screenTitle = Font.largeTitle.weight(.bold)
    /// En-têtes de rangées (Popular on Netflix, Trending Now).
    static let sectionTitle = Font.title3.weight(.semibold)
    /// Titre d'une fiche ou d'une vignette.
    static let cardTitle = Font.headline.weight(.bold)
    /// Seul style nommé du fichier Figma : « SF / Subheadline - Semibold ».
    static let cardSubtitle = Font.subheadline.weight(.semibold)
    /// Corps de texte courant : synopsis, descriptions.
    static let bodyText = Font.body.weight(.regular)
    /// Libellés de boutons (Play, Download, My List).
    static let buttonLabel = Font.callout.weight(.medium)
    /// Métadonnées : durée, année, classification.
    static let metadata = Font.footnote.weight(.regular)
    /// Mentions légales et libellés secondaires.
    static let captionLabel = Font.caption.weight(.regular)
    /// Libellés de la barre d'onglets (Home, Search, Coming Soon, More).
    static let tabLabel = Font.caption2.weight(.medium)
}
