import { describe, expect, it } from "vitest";

import {
  formatColors,
  formatDimensions,
  formatTextStyles,
  swiftMemberName,
  type DesignToken,
} from "./swift.ts";

const colorToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["color", "background", "primary"],
  $type: "color",
  value: "#141414",
  ...overrides,
});

const dimensionToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["spacing", "md"],
  $type: "dimension",
  value: "16px",
  ...overrides,
});

const textStyleToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["typography", "bodyText"],
  $type: "iosTextStyle",
  value: { textStyle: "body", fontWeight: 400 },
  ...overrides,
});

describe("swiftMemberName", () => {
  it("drops the category segment and camel-cases the rest", () => {
    expect(swiftMemberName(["color", "background", "primary"])).toBe("backgroundPrimary");
  });

  it("keeps a single remaining segment as-is", () => {
    expect(swiftMemberName(["spacing", "md"])).toBe("md");
  });

  it("lower-cases the first segment of an already camel-cased path", () => {
    expect(swiftMemberName(["typography", "bodyRegular"])).toBe("bodyRegular");
  });

  it("rejects a name that would start with a digit in Swift", () => {
    expect(() => swiftMemberName(["spacing", "2xl"])).toThrowError(/spacing\.2xl/);
  });

  it("rejects a Swift reserved keyword", () => {
    expect(() => swiftMemberName(["color", "default"])).toThrowError(/reserved/i);
  });

  it("rejects a path with no segment left after the category", () => {
    expect(() => swiftMemberName(["color"])).toThrowError(/color/);
  });
});

describe("formatColors", () => {
  it("emits a public Color extension with sRGB components", () => {
    const output = formatColors([colorToken()]);

    expect(output).toContain("public extension Color {");
    expect(output).toContain(
      "static let backgroundPrimary = Color(.sRGB, red: 0.078, green: 0.078, blue: 0.078, opacity: 1)",
    );
  });

  it("reads the alpha channel of an 8-digit hex", () => {
    const output = formatColors([
      colorToken({
        path: ["color", "background", "scrim"],
        value: "#00000099",
      }),
    ]);

    expect(output).toContain(
      "static let backgroundScrim = Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.6)",
    );
  });

  it("carries the token description over as a doc comment", () => {
    const output = formatColors([colorToken({ comment: "Fond principal de l'application." })]);

    expect(output).toContain("/// Fond principal de l'application.");
  });

  it("marks the file as generated", () => {
    expect(formatColors([colorToken()])).toContain(
      "// Generated by @repo/design-tokens — do not edit.",
    );
  });

  it("rejects a colour value that is not a hex string", () => {
    expect(() => formatColors([colorToken({ value: "rgb(20, 20, 20)" })])).toThrowError(
      /color\.background\.primary/,
    );
  });

  it("rejects an unresolved alias", () => {
    expect(() => formatColors([colorToken({ value: "{core.color.neutral.10}" })])).toThrowError(
      /unresolved/i,
    );
  });
});

describe("formatDimensions", () => {
  it("groups tokens into a namespaced enum of CGFloat constants", () => {
    const output = formatDimensions([dimensionToken()], {
      namespace: "Spacing",
    });

    expect(output).toContain("public enum Spacing {");
    expect(output).toContain("public static let md: CGFloat = 16");
  });

  it("keeps fractional pixel values", () => {
    const output = formatDimensions([dimensionToken({ path: ["spacing", "xs"], value: "2.5px" })], {
      namespace: "Spacing",
    });

    expect(output).toContain("public static let xs: CGFloat = 2.5");
  });

  it("accepts a unitless number", () => {
    const output = formatDimensions([dimensionToken({ value: 16 })], {
      namespace: "Spacing",
    });

    expect(output).toContain("public static let md: CGFloat = 16");
  });

  it("rejects a non-pixel unit", () => {
    expect(() =>
      formatDimensions([dimensionToken({ value: "1rem" })], {
        namespace: "Spacing",
      }),
    ).toThrowError(/spacing\.md/);
  });
});

describe("formatTextStyles", () => {
  it("emits a Font extension backed by an iOS system text style", () => {
    const output = formatTextStyles([textStyleToken()]);

    expect(output).toContain("public extension Font {");
    expect(output).toContain("static let bodyText = Font.body.weight(.regular)");
  });

  it("maps numeric font weights to SwiftUI weight names", () => {
    const output = formatTextStyles([
      textStyleToken({
        path: ["typography", "screenTitle"],
        value: { textStyle: "largeTitle", fontWeight: 700 },
      }),
    ]);

    expect(output).toContain("static let screenTitle = Font.largeTitle.weight(.bold)");
  });

  it("omits the weight modifier when the token does not specify one", () => {
    const output = formatTextStyles([textStyleToken({ value: { textStyle: "footnote" } })]);

    expect(output).toContain("static let bodyText = Font.footnote\n");
    expect(output).not.toContain(".weight(");
  });

  it("carries the token description over as a doc comment", () => {
    const output = formatTextStyles([textStyleToken({ comment: "Corps de texte courant." })]);

    expect(output).toContain("/// Corps de texte courant.");
  });

  it("rejects a text style that SwiftUI does not provide", () => {
    expect(() =>
      formatTextStyles([textStyleToken({ value: { textStyle: "gigantic" } })]),
    ).toThrowError(/gigantic/);
  });

  it("rejects an unsupported font weight", () => {
    expect(() =>
      formatTextStyles([textStyleToken({ value: { textStyle: "body", fontWeight: 450 } })]),
    ).toThrowError(/450/);
  });

  it("rejects an unresolved alias", () => {
    expect(() => formatTextStyles([textStyleToken({ value: "{typography.body}" })])).toThrowError(
      /unresolved/i,
    );
  });

  it("marks the file as generated", () => {
    expect(formatTextStyles([textStyleToken()])).toContain(
      "// Generated by @repo/design-tokens — do not edit.",
    );
  });

  it("rejects a token whose name would shadow a SwiftUI font member", () => {
    expect(() => formatTextStyles([textStyleToken({ path: ["typography", "body"] })])).toThrowError(
      /shadow/i,
    );
  });
});
