export type DesignToken = {
  readonly path: readonly string[];
  readonly $type: string;
  readonly value: unknown;
  readonly comment?: string;
};

const GENERATED_HEADER = [
  "// Generated by @repo/design-tokens — do not edit.",
  "// Source: packages/design-tokens/tokens/**",
  "",
  "import SwiftUI",
  "",
].join("\n");

const SWIFT_KEYWORDS = new Set([
  "associatedtype",
  "class",
  "default",
  "deinit",
  "enum",
  "extension",
  "fileprivate",
  "func",
  "import",
  "init",
  "inout",
  "internal",
  "let",
  "operator",
  "private",
  "protocol",
  "public",
  "repeat",
  "rethrows",
  "static",
  "struct",
  "subscript",
  "typealias",
  "var",
  "where",
  "while",
  "case",
  "break",
  "continue",
  "defer",
  "do",
  "else",
  "fallthrough",
  "for",
  "guard",
  "if",
  "in",
  "return",
  "switch",
  "catch",
  "throw",
  "throws",
  "try",
  "as",
  "is",
  "nil",
  "self",
  "super",
  "true",
  "false",
]);

const FONT_WEIGHTS = new Map<number, string>([
  [100, "ultraLight"],
  [200, "thin"],
  [300, "light"],
  [400, "regular"],
  [500, "medium"],
  [600, "semibold"],
  [700, "bold"],
  [800, "heavy"],
  [900, "black"],
]);

const tokenId = (path: readonly string[]): string => path.join(".");

export const swiftMemberName = (path: readonly string[]): string => {
  const [, ...segments] = path;

  if (segments.length === 0) {
    throw new Error(`Token "${tokenId(path)}" has no segment left once its category is dropped.`);
  }

  const [head, ...tail] = segments as [string, ...string[]];
  const name =
    head.charAt(0).toLowerCase() +
    head.slice(1) +
    tail.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("");

  if (/^[0-9]/.test(name)) {
    throw new Error(
      `Token "${tokenId(path)}" maps to "${name}", which is not a valid Swift identifier.`,
    );
  }

  if (SWIFT_KEYWORDS.has(name)) {
    throw new Error(`Token "${tokenId(path)}" maps to "${name}", a reserved Swift keyword.`);
  }

  return name;
};

const assertResolved = (value: unknown, path: readonly string[]): void => {
  if (typeof value === "string" && value.includes("{")) {
    throw new Error(`Unresolved alias for token "${tokenId(path)}": ${value}.`);
  }
};

const roundChannel = (value: number): string => String(Number(value.toFixed(3)));

const toSRGB = (
  value: unknown,
  path: readonly string[],
): { red: string; green: string; blue: string; opacity: string } => {
  assertResolved(value, path);

  const hex = typeof value === "string" ? /^#([0-9a-fA-F]{6}([0-9a-fA-F]{2})?)$/.exec(value) : null;

  if (hex === null) {
    throw new Error(
      `Token "${tokenId(path)}" is not a 6- or 8-digit hex colour: ${String(value)}.`,
    );
  }

  const digits = hex[1] as string;
  const channel = (index: number): number =>
    Number.parseInt(digits.slice(index * 2, index * 2 + 2), 16) / 255;

  return {
    red: roundChannel(channel(0)),
    green: roundChannel(channel(1)),
    blue: roundChannel(channel(2)),
    opacity: digits.length === 8 ? roundChannel(channel(3)) : "1",
  };
};

const toPoints = (value: unknown, path: readonly string[]): string => {
  assertResolved(value, path);

  if (typeof value === "number") {
    return String(value);
  }

  const points = typeof value === "string" ? /^(-?[0-9]+(\.[0-9]+)?)(px)?$/.exec(value) : null;

  if (points === null) {
    throw new Error(`Token "${tokenId(path)}" is not a pixel dimension: ${String(value)}.`);
  }

  return String(Number(points[1]));
};

const docComment = (token: DesignToken): readonly string[] =>
  token.comment === undefined ? [] : [`    /// ${token.comment}`];

export const formatColors = (tokens: readonly DesignToken[]): string => {
  const members = tokens.flatMap((token) => {
    const { red, green, blue, opacity } = toSRGB(token.value, token.path);

    return [
      ...docComment(token),
      `    static let ${swiftMemberName(token.path)} = Color(.sRGB, red: ${red}, green: ${green}, blue: ${blue}, opacity: ${opacity})`,
    ];
  });

  return [GENERATED_HEADER, "public extension Color {", ...members, "}", ""].join("\n");
};

export const formatDimensions = (
  tokens: readonly DesignToken[],
  { namespace }: { readonly namespace: string },
): string => {
  const members = tokens.flatMap((token) => [
    ...docComment(token),
    `    public static let ${swiftMemberName(token.path)}: CGFloat = ${toPoints(token.value, token.path)}`,
  ]);

  return [GENERATED_HEADER, `public enum ${namespace} {`, ...members, "}", ""].join("\n");
};

type TypographyValue = {
  readonly fontFamily: string;
  readonly fontSize: unknown;
  readonly fontWeight: unknown;
  readonly lineHeight: unknown;
};

const asTypography = (value: unknown, path: readonly string[]): TypographyValue => {
  assertResolved(value, path);

  if (typeof value !== "object" || value === null) {
    throw new Error(`Token "${tokenId(path)}" is not a composite typography value.`);
  }

  return value as TypographyValue;
};

const toFontWeight = (value: unknown, path: readonly string[]): string => {
  const weight = FONT_WEIGHTS.get(Number(value));

  if (weight === undefined) {
    throw new Error(`Token "${tokenId(path)}" uses the unsupported font weight ${String(value)}.`);
  }

  return weight;
};

export const formatTypography = (tokens: readonly DesignToken[]): string => {
  const fonts = tokens.flatMap((token) => {
    const typography = asTypography(token.value, token.path);

    return [
      ...docComment(token),
      `    static let ${swiftMemberName(token.path)} = Font.custom("${typography.fontFamily}", size: ${toPoints(typography.fontSize, token.path)}).weight(.${toFontWeight(typography.fontWeight, token.path)})`,
    ];
  });

  const lineHeights = tokens.map((token) => {
    const typography = asTypography(token.value, token.path);

    return `    public static let ${swiftMemberName(token.path)}: CGFloat = ${toPoints(typography.lineHeight, token.path)}`;
  });

  return [
    GENERATED_HEADER,
    "public extension Font {",
    ...fonts,
    "}",
    "",
    "public enum LineHeight {",
    ...lineHeights,
    "}",
    "",
  ].join("\n");
};
