import { describe, expect, it } from "vitest";

import {
  formatColors,
  formatDimensions,
  formatTypography,
  swiftMemberName,
  type DesignToken,
} from "./swift.ts";

const colorToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["color", "background", "primary"],
  $type: "color",
  value: "#141414",
  ...overrides,
});

const dimensionToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["spacing", "md"],
  $type: "dimension",
  value: "16px",
  ...overrides,
});

const typographyToken = (overrides: Partial<DesignToken> = {}): DesignToken => ({
  path: ["typography", "bodyRegular"],
  $type: "typography",
  value: {
    fontFamily: "Inter",
    fontSize: "17px",
    fontWeight: 400,
    lineHeight: "24px",
  },
  ...overrides,
});

describe("swiftMemberName", () => {
  it("drops the category segment and camel-cases the rest", () => {
    expect(swiftMemberName(["color", "background", "primary"])).toBe("backgroundPrimary");
  });

  it("keeps a single remaining segment as-is", () => {
    expect(swiftMemberName(["spacing", "md"])).toBe("md");
  });

  it("lower-cases the first segment of an already camel-cased path", () => {
    expect(swiftMemberName(["typography", "bodyRegular"])).toBe("bodyRegular");
  });

  it("rejects a name that would start with a digit in Swift", () => {
    expect(() => swiftMemberName(["spacing", "2xl"])).toThrowError(/spacing\.2xl/);
  });

  it("rejects a Swift reserved keyword", () => {
    expect(() => swiftMemberName(["color", "default"])).toThrowError(/reserved/i);
  });

  it("rejects a path with no segment left after the category", () => {
    expect(() => swiftMemberName(["color"])).toThrowError(/color/);
  });
});

describe("formatColors", () => {
  it("emits a public Color extension with sRGB components", () => {
    const output = formatColors([colorToken()]);

    expect(output).toContain("public extension Color {");
    expect(output).toContain(
      "static let backgroundPrimary = Color(.sRGB, red: 0.078, green: 0.078, blue: 0.078, opacity: 1)",
    );
  });

  it("reads the alpha channel of an 8-digit hex", () => {
    const output = formatColors([
      colorToken({
        path: ["color", "background", "scrim"],
        value: "#00000099",
      }),
    ]);

    expect(output).toContain(
      "static let backgroundScrim = Color(.sRGB, red: 0, green: 0, blue: 0, opacity: 0.6)",
    );
  });

  it("carries the token description over as a doc comment", () => {
    const output = formatColors([colorToken({ comment: "Fond principal de l'application." })]);

    expect(output).toContain("/// Fond principal de l'application.");
  });

  it("marks the file as generated", () => {
    expect(formatColors([colorToken()])).toContain(
      "// Generated by @repo/design-tokens — do not edit.",
    );
  });

  it("rejects a colour value that is not a hex string", () => {
    expect(() => formatColors([colorToken({ value: "rgb(20, 20, 20)" })])).toThrowError(
      /color\.background\.primary/,
    );
  });

  it("rejects an unresolved alias", () => {
    expect(() => formatColors([colorToken({ value: "{core.color.neutral.10}" })])).toThrowError(
      /unresolved/i,
    );
  });
});

describe("formatDimensions", () => {
  it("groups tokens into a namespaced enum of CGFloat constants", () => {
    const output = formatDimensions([dimensionToken()], {
      namespace: "Spacing",
    });

    expect(output).toContain("public enum Spacing {");
    expect(output).toContain("public static let md: CGFloat = 16");
  });

  it("keeps fractional pixel values", () => {
    const output = formatDimensions([dimensionToken({ path: ["spacing", "xs"], value: "2.5px" })], {
      namespace: "Spacing",
    });

    expect(output).toContain("public static let xs: CGFloat = 2.5");
  });

  it("accepts a unitless number", () => {
    const output = formatDimensions([dimensionToken({ value: 16 })], {
      namespace: "Spacing",
    });

    expect(output).toContain("public static let md: CGFloat = 16");
  });

  it("rejects a non-pixel unit", () => {
    expect(() =>
      formatDimensions([dimensionToken({ value: "1rem" })], {
        namespace: "Spacing",
      }),
    ).toThrowError(/spacing\.md/);
  });
});

describe("formatTypography", () => {
  it("emits a Font extension using the family, size and weight", () => {
    const output = formatTypography([typographyToken()]);

    expect(output).toContain("public extension Font {");
    expect(output).toContain(
      'static let bodyRegular = Font.custom("Inter", size: 17).weight(.regular)',
    );
  });

  it("maps numeric font weights to SwiftUI weight names", () => {
    const output = formatTypography([
      typographyToken({
        path: ["typography", "titleBold"],
        value: {
          fontFamily: "Inter",
          fontSize: "28px",
          fontWeight: 700,
          lineHeight: "34px",
        },
      }),
    ]);

    expect(output).toContain(".weight(.bold)");
  });

  it("exposes the line height as a companion CGFloat", () => {
    const output = formatTypography([typographyToken()]);

    expect(output).toContain("public enum LineHeight {");
    expect(output).toContain("public static let bodyRegular: CGFloat = 24");
  });

  it("rejects an unsupported font weight", () => {
    expect(() =>
      formatTypography([
        typographyToken({
          value: {
            fontFamily: "Inter",
            fontSize: "17px",
            fontWeight: 450,
            lineHeight: "24px",
          },
        }),
      ]),
    ).toThrowError(/450/);
  });
});
